INSERT INTO Tara VALUES (2, 'Rusia'),
                           (3, 'Canada'),
						   (4, 'Brazilia'),
                           (5, 'Australia'),
                           (6, 'USA'),
                           (7, 'UK'),
                           (8, 'India'),
                           (9, 'Spania'),
                           (10, 'Albania'),
                           (11, 'Italia'),
                           (12, 'Algeria'),
                           (13, 'Argentina'),
                           (14, 'Belgia'),
                           (15, 'Egipt'),
                           (16, 'Germania'),
						   (17, 'Ungaria'),
						   (18, 'Japonia');