INSERT INTO Oras VALUES (1, 'Cluj-Napoca', 1),
                        (2, 'Brasov', 1),
                        (3, 'Orastie', 1),
                        (4, 'Moscow', 2),
                        (5, 'Saint Petersburg', 2),
                        (6, 'Novosibirsk', 2),
                        (7, 'Toronto', 3),
						(8, 'Vancouver', 3),
						(9, 'Calgary', 3),
						(10, 'Rio de Janeiro', 4),
						(11, 'Manaus', 4),
						(12, 'Sao Paulo', 4),
						(13, 'Sydney', 5),
						(14, 'Melbourne', 5),
						(15, 'Perth', 5);