INSERT INTO Categorie VALUES (1, 'Lingvistica, dictionare'),
                            (2, 'Arta, arhitectura'),
                            (3, 'Biografii, memorii, jurnale'),
                            (4, 'Limbi straine'),
                            (5, 'Poezie, teatru, studii literare'),
                            (6, 'Fictiune'),
                            (7, 'Enciclopedii'),
                            (8, 'Istorie'),
                            (9, 'Religie'),
                            (10, 'Filosofie'),
							(11, 'Psihologie'),
							(12, 'Stiinte sociale'),
							(13, 'Politica'),
							(14, 'Drept'),
							(15, 'Eseistica'),
							(16, 'Dezvoltare personala'),
							(17, 'Raftul Brand Minds 2022'),
							(18, 'Psihologia emotiilor'),
							(19, 'Parenting'),
							(20, 'Umor'),
							(21, 'Raftul autorilor romani'),
							(22, 'Citit de scena 9'),
							(23, 'Moderni, contemporani'),
							(24, 'Fictiune mitologica si istorica'),
							(25, 'Fantasy'),
							(26, 'Romance'),
							(27, 'Young adult'),
							(28, 'Thriller'),
							(29, 'Horror'),
							(30, 'Comedy'),
							(31, 'Musical');
							